# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Abdel Raoof Olakara'
tagline:          'Tangled web dairy of Abdel Raoof'
description:      'This is personal site of Abdel Raoof Olakara'
url:              'http://abdelraoof.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/

# Author Details
author:         'Abdel Raoof Olakara'
linkedin:       'https://ae.linkedin.com/in/olakara/'
twitter:        'https://twitter.com/olakara'
facebook:       'https://www.facebook.com/olakara'
gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-53220404-1'

# Disqus
disqushandler: 'abdelraoof'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.10
